Polylink/Polylink/urls.py
from django.contrib import admin
from django.urls import path, include
import users.views

urlpatterns = [
    path('user/', include("users.urls")),
    path("post/", include("posts.urls")),
    path("stories/", include("stories.urls")),
    path('conversation/', include("conversations.urls")),
    path('', users.views.HomeView.as_view()),
]

Polylink/conversations/urls.py
from django.urls import path
from . import views

app_name = 'conversations'

urlpatterns = [
    path('<str:id>/', views.ConversationView.as_view(), name='conversation'),
    path('start/<str:id>/', views.ConversationView.as_view(), name='start-conversation'),
    path('message/<str:id>/', views.MessageView.as_view(), name='message'),
]

Polylink/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("post/", views.PostView.as_view(), name="post"),
    path("post/<str:id>/", views.PostView.as_view(), name="delete-post"),
    path("image/<str:id>/", views.PostImageView.as_view(), name="post-image"),
    path("like/<str:id>/", views.LikeView.as_view(), name="like-post"),
    path("comment/<str:id>/", views.CommentView.as_view(), name="comment-post"),
    path("detail/<str:id>/", views.PostDetailView.as_view(), name="post-detail"),
]

Polylink/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("home/", views.HomeView.as_view(), name="home"),
    path("explore/", views.ExploreView.as_view(), name="explore"),
    path("avatar/<str:id>/", views.AvatarView.as_view(), name="avatar"),
    path('search/<str:pattern>/', views.SearchView.as_view(), name='search'),
    path('following/', views.FollowingView.as_view(), name='get-followings'),
    path('following/<str:id>/', views.FollowingView.as_view(), name='follow'),
    path("notifications/<str:notification_id>/read/", views.MarkNotificationReadView.as_view(), name="mark-notification-read"),
    path("notifications/read/all/", views.MarkAllNotificationsReadView.as_view(), name="mark-all-read"),
    path("profile/<str:id>/", views.ProfileView.as_view(), name="profile"),
    path('relationship/graph/', views.RelationshipGraphView.as_view(), name='relationship-graph'),
    path('relationship/data/', views.RelationshipGraphDataView.as_view(), name='relationship-graph-data'),
]

Polylink/conversations/models.py
from django.db import models

# Create your models here.

Polylink/conversations/views.py
from django.shortcuts import render
from django.views import View
import db
import bson
from datetime import datetime, timezone
from django.http import HttpResponse, HttpRequest, JsonResponse
from django.urls import reverse

class ConversationView(View):
    def get(self, request, id):     
        # Fetch the user id
        user_id = db.get_user_id(request)

        # Fetch the other user whom this user is chatting with
        participants_ids = db.db.conversations.find_one({"_id": bson.ObjectId(id)})['participants']
        if participants_ids[0] == user_id:
            other_user_id = participants_ids[1]
        else:
            other_user_id = participants_ids[0]
        other_user = db.db.users.find_one({'_id':other_user_id}, {"_id": 0, 'id': '$_id', 'first_name': 1, 'last_name': 1})  

        messages = list(db.db.messages.find({'conversation': bson.ObjectId(id)}))
    
        return render(request, 'conversations/inside-conversation.html', {'conversation_id': id , 'messages': messages, 'user_id': user_id, 'other_user': other_user})
    
    def post(self, request, id):
        user_id = db.get_user_id(request)
        
        # Verify if the other_user_id is not the user itseft
        if user_id == id:
            return JsonResponse(data={'error': 'You cannot talk to your self bro, what u doing 🤨'})
        
        # Verify if the other user does not already have a discussion
        conversation = db.db.conversations.find_one({
            '$and': [
                {'participants': {'$in': [bson.ObjectId(user_id)]}},
                {'participants': {'$in': [bson.ObjectId(id)]}},
            ]
        })
 
        if conversation:
            return JsonResponse(data={'error': 'Bro, you are already in talk with this guys, come on man 😭'})
        
        conversation = db.db.conversations.insert_one({
            'participants': [bson.ObjectId(user_id), bson.ObjectId(id)]
        })

        # Return to the client the id of the newly inserted conversation
        conversation_src = reverse('conversations:conversation', kwargs={'id':str(conversation.inserted_id)})
        response = JsonResponse(data={'conversation_src': conversation_src})
        return response

class MessageView(View):
    def get(self, request, id):
        pass
    
    def post(self, request:HttpRequest, id):
        user_id = db.get_user_id(request)
        content = request.body.decode('utf-8')
        message = db.db.messages.insert_one({
            'sender': bson.ObjectId(user_id),
            'content': content,
            'date': datetime.now(timezone.utc),
            'seen': False,
            'conversation': bson.ObjectId(id),
        })

        # Update the last message of the conversation
        db.db.conversations.update_one(
            {'_id': bson.ObjectId(id)}, 
            {'$set': {
                'last_message': message.inserted_id,
            }}
        )

        response = HttpResponse()
        response.status_code = 204  # Nothing to return
        return response

Polylink/templates/conversations/conversation.html
<div class="conversations-wrapper">
    <aside class="conversations">
    <div class="conversations-header">
        <p>Conversations</p>
        <div class="search-bar">
        <i class="bi bi-search search-icon"></i>
        <input type="text" placeholder="Search conversations" />
        </div>
        <div class="tabs">
        <span class="active">All</span>
        <span>Unread</span>
        </div>
    </div>

    <div class="conversation-list">
        {% for conversation in conversations %}
        <div class="conversation" url={% url 'conversations:conversation' id=conversation.id %} />
            <div class="avatar">
            <img src={% url "users:avatar" id=conversation.other_user.id %} alt="profil">
            </div>
            <div>
            <h4>{{conversation.other_user.first_name}} {{conversation.other_user.last_name}}</h4>
            <p class='last-message-view'>{{ conversation.last_message.content|slice:'0:10' }}...</p>
            </div>
            <div class="infos">
            <p>{{ conversation.last_message.date }}</p>
            <span style='white-space: pre;'> </span>
            </div>
        </div>
        {% endfor %}
    </div>
    </aside>

    <aside class="inside-conversation"></aside>
</div>

Polylink/templates/conversations/inside-conversation.html
{% load static %}
{% comment %} <aside class="inside-conversation"> {% endcomment %}
      <div class="header">
        <i class="bi bi-arrow-left go-back-button"></i>
        <p>{{ other_user.first_name }} {{ other_user.last_name }}</p>
        <div class="avatar message-avatar">
          <img src={% url "users:avatar" id=other_user.id %} alt="profil">
        </div>
      </div>

      <div class="body">
        {% for message in messages %}
           <div class="{% if user_id == message.sender %}sent{% endif %} message">
                <p class="text">{{ message.content }}</p>  <!-- Be careful, this element has the white-space property set to pre-->
           </div>
        {% endfor %}
      </div> 

      <div class="write-message" url={% url "conversations:message" id=conversation_id %}>
        <label for="attach" class="attach-doc-button">
          <i title="attach an document" class="bi bi-plus-lg"></i>
        </label>
        <input type="file" name="image" id="attach">
        <textarea spellcheck="false" name="message" placeholder="Message..."></textarea>
        {% comment %} <i title="write-emoji" class="bi bi-emoji-smile write-emoji"></i> {% endcomment %}
        <i title="send" class="bi bi-send send-button"></i>
      </div>
{% comment %} </aside> {% endcomment %}